[package]
name = "wr_azul_glyph_rasterizer"
version = "0.1.0"
authors = ["The Mozilla Project Developers", "Azul Developers"]
description = "A pure-rust, API-compatible glyph rasterizer for WebRender using azul-layout and tiny-skia"
license = "MPL-2.0"
edition = "2021"

[features]
# By default, no features are enabled. The consumer (WebRender) will select them.
default = []

# --- Compatibility Features ---
# These features are kept for API compatibility with webrender's Cargo.toml.
# They enabled C-based FreeType linking in the original crate. Here, they do nothing,
# allowing this pure-Rust crate to be a drop-in replacement without modifying webrender.
dynamic_freetype = []
static_freetype = []

# --- Core Features ---
# Enable serialization/deserialization for capturing and replaying render commands.
capture = ["api/serialize"]
replay = ["api/deserialize"]

[dependencies]
# ===== Original WebRender Dependencies (Pure Rust) =====
api = { version = "0.62.0", package = "webrender_api", path = "../api" }
euclid = "0.22.10"
rayon = "1"
smallvec = "1"
tracy-rs = "0.1.2"
log = "0.4"
lazy_static = "1"
fxhash = "0.2.1"
# Replaces FreeType, CoreText, and DirectWrite.
azul-layout = { path = "../../layout" }
azul-core = { path = "../../core" }
tiny-skia = "0.11"


[dev-dependencies]
# Kept for potential local testing, matching the original crate's setup.
env_logger = { version = "0.10", default-features = false }
