[workspace]
resolver = "2"
members = [
    # "examples" # compiled in CI: depend on 
    # "api" # generated in CI: Rust bindings to the "dll" module, depends on NOTHING
    "dll", # dll module with auto-gen C functions (optional pyO3 support), depends on layout, core and css
    "doc", # doc / test generator, depends on layout, core and css
    "layout", # layout depends on core + css
    "core", # core depends on css
    "css", # CSS parser, does not depend on anything else
]

[workspace.dependencies]
glean = "60.5.0"
gleam = "0.15.1"
